
export const estadoPorDdd = {
 1: "US",          // Estados Unidos / Canadá
  7: "RU",          // Rusia / Kazajistán
  20: "EG",
  27: "ZA",
  30: "GR",
  31: "NL",
  32: "BE",
  33: "FR",
  34: "ES",
  36: "HU",
  39: "IT",
  40: "RO",
  41: "CH",
  43: "AT",
  44: "GB",
  45: "DK",
  46: "SE",
  47: "NO",
  48: "PL",
  49: "DE",
  51: "PE",
  52: "MX",
  53: "CU",
  54: "AR",
  55: "BR",
  56: "CL",
  57: "CO",
  58: "VE",
  60: "MY",
  61: "AU",
  62: "ID",
  63: "PH",
  64: "NZ",
  65: "SG",
  66: "TH",
  81: "JP",
  82: "KR",
  84: "VN",
  86: "CN",
  90: "TR",
  91: "IN",
  92: "PK",
  93: "AF",
  94: "LK",
  95: "MM",
  98: "IR",
  211: "SS",
  212: "MA",
  213: "DZ",
  216: "TN",
  218: "LY",
  220: "GM",
  221: "SN",
  222: "MR",
  223: "ML",
  224: "GN",
  225: "CI",
  226: "BF",
  227: "NE",
  228: "TG",
  229: "BJ",
  230: "MU",
  231: "LR",
  232: "SL",
  233: "GH",
  234: "NG",
  235: "TD",
  236: "CF",
  237: "CM",
  238: "CV",
  239: "ST",
  240: "GQ",
  241: "GA",
  242: "CG",
  243: "CD",
  244: "AO",
  245: "GW",
  246: "IO",
  247: "AC",  // Ascensión (no oficial, AC se usa informalmente)
  248: "SC",
  249: "SD",
  250: "RW",
  251: "ET",
  252: "SO",
  253: "DJ",
  254: "KE",
  255: "TZ",
  256: "UG",
  257: "BI",
  258: "MZ",
  260: "ZM",
  261: "MG",
  262: "RE",
  263: "ZW",
  264: "NA",
  265: "MW",
  266: "LS",
  267: "BW",
  268: "SZ",
  269: "KM",
  290: "SH",
  291: "ER",
  297: "AW",
  298: "FO",
  299: "GL",
  350: "GI",
  351: "PT",
  352: "LU",
  353: "IE",
  354: "IS",
  355: "AL",
  356: "MT",
  357: "CY",
  358: "FI",
  359: "BG",
  370: "LT",
  371: "LV",
  372: "EE",
  373: "MD",
  374: "AM",
  375: "BY",
  376: "AD",
  377: "MC",
  378: "SM",
  379: "VA",
  380: "UA",
  381: "RS",
  382: "ME",
  383: "XK",  // Kosovo (no oficialmente reconocido en ISO, pero se usa "XK")
  385: "HR",
  386: "SI",
  387: "BA",
  389: "MK",
  420: "CZ",
  421: "SK",
  423: "LI",
  500: "FK",
  501: "BZ",
  502: "GT",
  503: "SV",
  504: "HN",
  505: "NI",
  506: "CR",
  507: "PA",
  508: "PM",
  509: "HT",
  590: "GP",
  591: "BO",
  592: "GY",
  593: "EC",
  594: "GF",
  595: "PY",
  596: "MQ",
  597: "SR",
  598: "UY",
  599: "CW", // Curazao (antes Antillas Neerlandesas)
  670: "TL",
  672: "AQ", // Antártida
  673: "BN",
  674: "NR",
  675: "PG",
  676: "TO",
  677: "SB",
  678: "VU",
  679: "FJ",
  680: "PW",
  681: "WF",
  682: "CK",
  683: "NU",
  685: "WS",
  686: "KI",
  687: "NC",
  688: "TV",
  689: "PF",
  690: "TK",
  691: "FM",
  692: "MH",
  850: "KP",
  852: "HK",
  853: "MO",
  855: "KH",
  856: "LA",
  880: "BD",
  886: "TW",
  960: "MV",
  961: "LB",
  962: "JO",
  963: "SY",
  964: "IQ",
  965: "KW",
  966: "SA",
  967: "YE",
  968: "OM",
  970: "PS",
  971: "AE",
  972: "IL",
  973: "BH",
  974: "QA",
  975: "BT",
  976: "MN",
  977: "NP",
  992: "TJ",
  993: "TM",
  994: "AZ",
  995: "GE",
  996: "KG",
  998: "UZ"
}

export const dddsPorEstado = {
  US: ['1'],
  CA: ['1'],
  RU: ['7'],
  KZ: ['7'],
  EG: ['20'],
  ZA: ['27'],
  GR: ['30'],
  NL: ['31'],
  BE: ['32'],
  FR: ['33'],
  ES: ['34'],
  HU: ['36'],
  IT: ['39'],
  RO: ['40'],
  CH: ['41'],
  AT: ['43'],
  GB: ['44'],
  DK: ['45'],
  SE: ['46'],
  NO: ['47'],
  PL: ['48'],
  DE: ['49'],
  PE: ['51'],
  MX: ['52'],
  CU: ['53'],
  AR: ['54'],
  BR: ['55'],
  CL: ['56'],
  CO: ['57'],
  VE: ['58'],
  MY: ['60'],
  AU: ['61'],
  ID: ['62'],
  PH: ['63'],
  NZ: ['64'],
  SG: ['65'],
  TH: ['66'],
  JP: ['81'],
  KR: ['82'],
  VN: ['84'],
  CN: ['86'],
  TR: ['90'],
  IN: ['91'],
  PK: ['92'],
  AF: ['93'],
  LK: ['94'],
  MM: ['95'],
  IR: ['98'],
  SS: ['211'],
  MA: ['212'],
  DZ: ['213'],
  TN: ['216'],
  LY: ['218'],
  GM: ['220'],
  SN: ['221'],
  MR: ['222'],
  ML: ['223'],
  GN: ['224'],
  CI: ['225'],
  BF: ['226'],
  NE: ['227'],
  TG: ['228'],
  BJ: ['229'],
  MU: ['230'],
  LR: ['231'],
  SL: ['232'],
  GH: ['233'],
  NG: ['234'],
  TD: ['235'],
  CF: ['236'],
  CM: ['237'],
  CV: ['238'],
  ST: ['239'],
  GQ: ['240'],
  GA: ['241'],
  CG: ['242'],
  CD: ['243'],
  AO: ['244'],
  GW: ['245'],
  IO: ['246'],
  SH: ['247'],
  SC: ['248'],
  SD: ['249'],
  RW: ['250'],
  ET: ['251'],
  SO: ['252'],
  DJ: ['253'],
  KE: ['254'],
  TZ: ['255'],
  UG: ['256'],
  BI: ['257'],
  MZ: ['258'],
  ZM: ['260'],
  MG: ['261'],
  RE: ['262'],
  ZW: ['263'],
  NA: ['264'],
  MW: ['265'],
  LS: ['266'],
  BW: ['267'],
  SZ: ['268'],
  KM: ['269'],
  SH: ['290'],
  ER: ['291'],
  AW: ['297'],
  FO: ['298'],
  GL: ['299'],
  GI: ['350'],
  PT: ['351'],
  LU: ['352'],
  IE: ['353'],
  IS: ['354'],
  AL: ['355'],
  MT: ['356'],
  CY: ['357'],
  FI: ['358'],
  BG: ['359'],
  LT: ['370'],
  LV: ['371'],
  EE: ['372'],
  MD: ['373'],
  AM: ['374'],
  BY: ['375'],
  AD: ['376'],
  MC: ['377'],
  SM: ['378'],
  VA: ['379'],
  UA: ['380'],
  RS: ['381'],
  ME: ['382'],
  XK: ['383'],
  HR: ['385'],
  SI: ['386'],
  BA: ['387'],
  MK: ['389'],
  CZ: ['420'],
  SK: ['421'],
  LI: ['423'],
  FK: ['500'],
  BZ: ['501'],
  GT: ['502'],
  SV: ['503'],
  HN: ['504'],
  NI: ['505'],
  CR: ['506'],
  PA: ['507'],
  PM: ['508'],
  HT: ['509'],
  GP: ['590'],
  BO: ['591'],
  GY: ['592'],
  EC: ['593'],
  GF: ['594'],
  PY: ['595'],
  MQ: ['596'],
  SR: ['597'],
  UY: ['598'],
  AN: ['599'],
  TL: ['670'],
  AQ: ['672'],
  BN: ['673'],
  NR: ['674'],
  PG: ['675'],
  TO: ['676'],
  SB: ['677'],
  VU: ['678'],
  FJ: ['679'],
  PW: ['680'],
  WF: ['681'],
  CK: ['682'],
  NU: ['683'],
  WS: ['685'],
  KI: ['686'],
  NC: ['687'],
  TV: ['688'],
  PF: ['689'],
  TK: ['690'],
  FM: ['691'],
  MH: ['692'],
  KP: ['850'],
  HK: ['852'],
  MO: ['853'],
  KH: ['855'],
  LA: ['856'],
  TW: ['886'],
  MV: ['960'],
  LB: ['961'],
  JO: ['962'],
  SY: ['963'],
  IQ: ['964'],
  KW: ['965'],
  SA: ['966'],
  YE: ['967'],
  OM: ['968'],
  PS: ['970'],
  AE: ['971'],
  IL: ['972'],
  BH: ['973'],
  QA: ['974'],
  BT: ['975'],
  MN: ['976'],
  NP: ['977'],
  TJ: ['992'],
  TM: ['993'],
  AZ: ['994'],
  GE: ['995'],
  KG: ['996'],
  UZ: ['998']
}

export const estadosBR = [
  { nome: 'Estados Unidos / Canadá', sigla: 'US' },
{ nome: 'Rusia / Kazajistán', sigla: 'RU' },
{ nome: 'Egipto', sigla: 'EG' },
{ nome: 'Sudáfrica', sigla: 'ZA' },
{ nome: 'Grecia', sigla: 'GR' },
{ nome: 'Países Bajos', sigla: 'NL' },
{ nome: 'Bélgica', sigla: 'BE' },
{ nome: 'Francia', sigla: 'FR' },
{ nome: 'España', sigla: 'ES' },
{ nome: 'Hungría', sigla: 'HU' },
{ nome: 'Italia', sigla: 'IT' },
{ nome: 'Rumanía', sigla: 'RO' },
{ nome: 'Suiza', sigla: 'CH' },
{ nome: 'Austria', sigla: 'AT' },
{ nome: 'Reino Unido', sigla: 'GB' },
{ nome: 'Dinamarca', sigla: 'DK' },
{ nome: 'Suecia', sigla: 'SE' },
{ nome: 'Noruega', sigla: 'NO' },
{ nome: 'Polonia', sigla: 'PL' },
{ nome: 'Alemania', sigla: 'DE' },
{ nome: 'Perú', sigla: 'PE' },
{ nome: 'México', sigla: 'MX' },
{ nome: 'Cuba', sigla: 'CU' },
{ nome: 'Argentina', sigla: 'AR' },
{ nome: 'Brasil', sigla: 'BR' },
{ nome: 'Chile', sigla: 'CL' },
{ nome: 'Colombia', sigla: 'CO' },
{ nome: 'Venezuela', sigla: 'VE' },
{ nome: 'Malasia', sigla: 'MY' },
{ nome: 'Australia', sigla: 'AU' },
{ nome: 'Indonesia', sigla: 'ID' },
{ nome: 'Filipinas', sigla: 'PH' },
{ nome: 'Nueva Zelanda', sigla: 'NZ' },
{ nome: 'Singapur', sigla: 'SG' },
{ nome: 'Tailandia', sigla: 'TH' },
{ nome: 'Japón', sigla: 'JP' },
{ nome: 'Corea del Sur', sigla: 'KR' },
{ nome: 'Vietnam', sigla: 'VN' },
{ nome: 'China', sigla: 'CN' },
{ nome: 'Turquía', sigla: 'TR' },
{ nome: 'India', sigla: 'IN' },
{ nome: 'Pakistán', sigla: 'PK' },
{ nome: 'Afganistán', sigla: 'AF' },
{ nome: 'Sri Lanka', sigla: 'LK' },
{ nome: 'Myanmar', sigla: 'MM' },
{ nome: 'Irán', sigla: 'IR' },
{ nome: 'Sudán del Sur', sigla: 'SS' },
{ nome: 'Marruecos', sigla: 'MA' },
{ nome: 'Argelia', sigla: 'DZ' },
{ nome: 'Túnez', sigla: 'TN' },
{ nome: 'Libia', sigla: 'LY' },
{ nome: 'Gambia', sigla: 'GM' },
{ nome: 'Senegal', sigla: 'SN' },
{ nome: 'Mauritania', sigla: 'MR' },
{ nome: 'Malí', sigla: 'ML' },
{ nome: 'Guinea', sigla: 'GN' },
{ nome: 'Costa de Marfil', sigla: 'CI' },
{ nome: 'Burkina Faso', sigla: 'BF' },
{ nome: 'Níger', sigla: 'NE' },
{ nome: 'Togo', sigla: 'TG' },
{ nome: 'Benín', sigla: 'BJ' },
{ nome: 'Mauricio', sigla: 'MU' },
{ nome: 'Liberia', sigla: 'LR' },
{ nome: 'Sierra Leona', sigla: 'SL' },
{ nome: 'Ghana', sigla: 'GH' },
{ nome: 'Nigeria', sigla: 'NG' },
{ nome: 'Chad', sigla: 'TD' },
{ nome: 'República Centroafricana', sigla: 'CF' },
{ nome: 'Camerún', sigla: 'CM' },
{ nome: 'Cabo Verde', sigla: 'CV' },
{ nome: 'Santo Tomé y Príncipe', sigla: 'ST' },
{ nome: 'Guinea Ecuatorial', sigla: 'GQ' },
{ nome: 'Gabón', sigla: 'GA' },
{ nome: 'Congo', sigla: 'CG' },
{ nome: 'República Democrática del Congo', sigla: 'CD' },
{ nome: 'Angola', sigla: 'AO' },
{ nome: 'Guinea-Bisáu', sigla: 'GW' },
{ nome: 'Territorio Británico del Océano Índico', sigla: 'IO' },
{ nome: 'Isla Ascensión', sigla: 'AC' },
{ nome: 'Seychelles', sigla: 'SC' },
{ nome: 'Sudán', sigla: 'SD' },
{ nome: 'Ruanda', sigla: 'RW' },
{ nome: 'Etiopía', sigla: 'ET' },
{ nome: 'Somalia', sigla: 'SO' },
{ nome: 'Yibuti', sigla: 'DJ' },
{ nome: 'Kenia', sigla: 'KE' },
{ nome: 'Tanzania', sigla: 'TZ' },
{ nome: 'Uganda', sigla: 'UG' },
{ nome: 'Burundi', sigla: 'BI' },
{ nome: 'Mozambique', sigla: 'MZ' },
{ nome: 'Zambia', sigla: 'ZM' },
{ nome: 'Madagascar', sigla: 'MG' },
{ nome: 'Reunión', sigla: 'RE' },
{ nome: 'Zimbabue', sigla: 'ZW' },
{ nome: 'Namibia', sigla: 'NA' },
{ nome: 'Malaui', sigla: 'MW' },
{ nome: 'Lesoto', sigla: 'LS' },
{ nome: 'Botsuana', sigla: 'BW' },
{ nome: 'Esuatini', sigla: 'SZ' },
{ nome: 'Comoras', sigla: 'KM' },
{ nome: 'Santa Elena', sigla: 'SH' },
{ nome: 'Eritrea', sigla: 'ER' },
{ nome: 'Aruba', sigla: 'AW' },
{ nome: 'Islas Feroe', sigla: 'FO' },
{ nome: 'Groenlandia', sigla: 'GL' },
{ nome: 'Gibraltar', sigla: 'GI' },
{ nome: 'Portugal', sigla: 'PT' },
{ nome: 'Luxemburgo', sigla: 'LU' },
{ nome: 'Irlanda', sigla: 'IE' },
{ nome: 'Islandia', sigla: 'IS' },
{ nome: 'Albania', sigla: 'AL' },
{ nome: 'Malta', sigla: 'MT' },
{ nome: 'Chipre', sigla: 'CY' },
{ nome: 'Finlandia', sigla: 'FI' },
{ nome: 'Bulgaria', sigla: 'BG' },
{ nome: 'Lituania', sigla: 'LT' },
{ nome: 'Letonia', sigla: 'LV' },
{ nome: 'Estonia', sigla: 'EE' },
{ nome: 'Moldavia', sigla: 'MD' },
{ nome: 'Armenia', sigla: 'AM' },
{ nome: 'Bielorrusia', sigla: 'BY' },
{ nome: 'Andorra', sigla: 'AD' },
{ nome: 'Mónaco', sigla: 'MC' },
{ nome: 'San Marino', sigla: 'SM' },
{ nome: 'Ciudad del Vaticano', sigla: 'VA' },
{ nome: 'Ucrania', sigla: 'UA' },
{ nome: 'Serbia', sigla: 'RS' },
{ nome: 'Montenegro', sigla: 'ME' },
{ nome: 'Kosovo', sigla: 'XK' },
{ nome: 'Croacia', sigla: 'HR' },
{ nome: 'Eslovenia', sigla: 'SI' },
{ nome: 'Bosnia y Herzegovina', sigla: 'BA' },
{ nome: 'Macedonia del Norte', sigla: 'MK' },
{ nome: 'Chequia', sigla: 'CZ' },
{ nome: 'Eslovaquia', sigla: 'SK' },
{ nome: 'Liechtenstein', sigla: 'LI' },
{ nome: 'Islas Malvinas', sigla: 'FK' },
{ nome: 'Belice', sigla: 'BZ' },
{ nome: 'Guatemala', sigla: 'GT' },
{ nome: 'El Salvador', sigla: 'SV' },
{ nome: 'Honduras', sigla: 'HN' },
{ nome: 'Nicaragua', sigla: 'NI' },
{ nome: 'Costa Rica', sigla: 'CR' },
{ nome: 'Panamá', sigla: 'PA' },
{ nome: 'San Pedro y Miquelón', sigla: 'PM' },
{ nome: 'Haití', sigla: 'HT' },
{ nome: 'Guadalupe', sigla: 'GP' },
{ nome: 'Bolivia', sigla: 'BO' },
{ nome: 'Guyana', sigla: 'GY' },
{ nome: 'Ecuador', sigla: 'EC' },
{ nome: 'Guayana Francesa', sigla: 'GF' },
{ nome: 'Paraguay', sigla: 'PY' },
{ nome: 'Martinica', sigla: 'MQ' },
{ nome: 'Surinam', sigla: 'SR' },
{ nome: 'Uruguay', sigla: 'UY' },
{ nome: 'Curazao', sigla: 'CW' },
{ nome: 'Timor Oriental', sigla: 'TL' },
{ nome: 'Antártida', sigla: 'AQ' },
{ nome: 'Brunéi', sigla: 'BN' },
{ nome: 'Nauru', sigla: 'NR' },
{ nome: 'Papúa Nueva Guinea', sigla: 'PG' },
{ nome: 'Tonga', sigla: 'TO' },
{ nome: 'Islas Salomón', sigla: 'SB' },
{ nome: 'Vanuatu', sigla: 'VU' },
{ nome: 'Fiyi', sigla: 'FJ' },
{ nome: 'Palaos', sigla: 'PW' },
{ nome: 'Wallis y Futuna', sigla: 'WF' },
{ nome: 'Islas Cook', sigla: 'CK' },
{ nome: 'Niue', sigla: 'NU' },
{ nome: 'Samoa', sigla: 'WS' },
{ nome: 'Kiribati', sigla: 'KI' },
{ nome: 'Nueva Caledonia', sigla: 'NC' },
{ nome: 'Tuvalu', sigla: 'TV' },
{ nome: 'Polinesia Francesa', sigla: 'PF' },
{ nome: 'Tokelau', sigla: 'TK' },
{ nome: 'Micronesia', sigla: 'FM' },
{ nome: 'Islas Marshall', sigla: 'MH' },
{ nome: 'Corea del Norte', sigla: 'KP' },
{ nome: 'Hong Kong', sigla: 'HK' },
{ nome: 'Macao', sigla: 'MO' },
{ nome: 'Camboya', sigla: 'KH' },
{ nome: 'Laos', sigla: 'LA' },
{ nome: 'Bangladés', sigla: 'BD' },
{ nome: 'Taiwán', sigla: 'TW' },
{ nome: 'Maldivas', sigla: 'MV' },
{ nome: 'Líbano', sigla: 'LB' },
{ nome: 'Jordania', sigla: 'JO' },
{ nome: 'Siria', sigla: 'SY' },
{ nome: 'Irak', sigla: 'IQ' },
{ nome: 'Kuwait', sigla: 'KW' },
{ nome: 'Arabia Saudita', sigla: 'SA' },
{ nome: 'Yemen', sigla: 'YE' },
{ nome: 'Omán', sigla: 'OM' },
{ nome: 'Palestina', sigla: 'PS' },
{ nome: 'Emiratos Árabes Unidos', sigla: 'AE' },
{ nome: 'Israel', sigla: 'IL' },
{ nome: 'Baréin', sigla: 'BH' },
{ nome: 'Catar', sigla: 'QA' },
{ nome: 'Bután', sigla: 'BT' },
{ nome: 'Mongolia', sigla: 'MN' },
{ nome: 'Nepal', sigla: 'NP' },
{ nome: 'Tayikistán', sigla: 'TJ' },
{ nome: 'Turkmenistán', sigla: 'TM' },
{ nome: 'Azerbaiyán', sigla: 'AZ' },
{ nome: 'Georgia', sigla: 'GE' },
{ nome: 'Kirguistán', sigla: 'KG' },
{ nome: 'Uzbekistán', sigla: 'UZ' }

]

export const messagesLog = {
  access: {
    message: 'Accedió al ticket',
    color: 'grey-8',
    icon: 'mdi-eye'
  },
  closed: {
    message: 'resuelto el ticket',
    color: 'positive',
    icon: 'mdi-check-circle-outline'
  },
  create: {
    message: 'ticket creado',
    color: 'green-6',
    icon: 'mdi-plus-circle'
  },
  delete: {
    message: 'Eliminado el ticket',
    color: 'negative',
    icon: 'mdi-delete'
  },
  open: {
    message: 'Servicio iniciado',
    color: 'primary',
    icon: 'mdi-play-circle-outline'
  },
  pending: {
    message: 'Servicio devuelto al departamento pendiente',
    color: 'amber',
    icon: 'mdi-account-convert'
  },
  transfered: {
    message: 'Transferido el servicio',
    color: 'teal-3',
    icon: 'mdi-account-arrow-right'
  },
  receivedTransfer: {
    message: 'Servicio recibido por transferencia.',
    color: 'teal-5',
    icon: 'mdi-account-arrow-left'
  },
  queue: {
    message: 'Bot: departamento definido',
    color: 'green-2',
    icon: 'mdi-arrow-decision'
  },
  userDefine: {
    message: 'Bot: Definido por el usuario',
    color: 'cyan-2',
    icon: 'mdi-account-check'
  },
  retriesLimitQueue: {
    message: 'Bot: departamento definido (límite de intentos)',
    color: 'green-2',
    icon: 'mdi-arrow-decision'
  },
  retriesLimitUserDefine: {
    message: 'Bot: Definido por el usuario (límite de intentos)',
    color: 'cyan-2',
    icon: 'mdi-account-check'
  },
  chatBot: {
    message: 'ChatBot iniciado',
    color: 'blue-4',
    icon: 'mdi-robot'
  },
  autoClose: {
    message: 'Bot: Atención al cliente cerrada',
    color: 'blue-8',
    icon: 'mdi-check-circle-outline'
  }
}
